# https://nixpacks.com/docs/providers/php
[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
  "mkdir -p storage/framework/cache storage/framework/sessions storage/framework/views storage/logs bootstrap/cache",
  "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
